### PR TITLE
Add ESM version

### LINKED ISSUE #337: ESM version
Do you have plans to support an ESM module output?
As `"module": "path/to/esm-file.js"` or via `exports` in package.json?

I'd be happy to work on it and discuss the best approach to keep things maximum compatible or introduce a new major if needed.

### PR DESCRIPTION
**Pull request by bashmish**
Fixes #337

### CODE REVIEW

**Comment by tscanlin** [comment]
Hey, thanks for the PR! This looks good to me. How would this affect imports of other sub-dependencies for non-esm projects? I guess since utils wasn't touched it shouldn't be a big deal.

Thanks again!

**Comment by bashmish** [comment]
> Hey, thanks for the PR! This looks good to me. How would this affect imports of other sub-dependencies for non-esm projects? I guess since utils wasn't touched it shouldn't be a big deal.
> 
> Thanks again!

It shouldn't impact subdependencies for non-ESM.

Do you have some project where we can test if this works? I can make a prerelease version with `@bashmish/tocbot` for now to be able to test it on a real project.

**Review by tscanlin — COMMENTED** [review]
Should there be a test for .cjs.js require style of use? I don't currently have a project that is using it aside from in the project itself. But running the local development server and requiring from there may help to test it.

**Comment by bashmish** [comment]
> Should there be a test for .cjs.js require style of use?
@tscanlin `static/js/tocbot.js` is generated with the input file of `index-dist.js` with a UMD wrapper and is injected like before via a script tag, so I thought that would be sufficient to test it like that, despite that test cases are loaded from a ESM. The latter is done, because it was easy to use such file to load in both ESM and UMD versions and reuse tests, it's only the tests cases which are loaded like that, the initialisation of the library remained the same I think for UMD, and for ESM there is a separate new initialisation file. Maybe I didn't get some nuances in how UMD was tested before, would be nice if you can elaborate.

> I don't currently have a project that is using it aside from in the project itself. But running the local development server and requiring from there may help to test it.
What particular way of loading do you want to test?
I used ESM and a simple script. ESM is standard, injecting a script via a script tag and exposing on the `window.tocbot` is also standard, no special tools are involved. Then there would be more ways to load it using different tools, with a spectrum between old-school require.js and new-school like Vite.

**Comment by tscanlin** [comment]
Thanks for the PR!!

**Comment by tscanlin** [comment]
`tocbot@4.27.0` is published with this change. Thanks @bashmish!

**Pull request merged**
