### PR TITLE
Support passing a DOM element into init

### PR DESCRIPTION
**Pull request by dkniffin**
This is untested, but I think it is pretty close to a working solution

### CODE REVIEW

**Comment by tscanlin** [comment]
Thanks for the PR! I re-opened the issue. Does this PR actually work?

Also, is there a way this can be made to be non-breaking? Currently there's the `contentSelector` option, etc. and it would be great to support both so that this is a non-breaking change. What do you think of that?

Really appreciate the PR though, this is a great idea! Thank you!

**Comment by dkniffin** [comment]
@tscanlin I haven't tested it yet. I was putting it out there as a "here's the gist of what's needed".

I think this is non-breaking. It should support both the `contentSelector` and the `contentElement` options, depending on what's given.

If you're open to the idea, I can finish it up and test it.

**Comment by tscanlin** [comment]
That would be great! If you don't have time to test let me know and I can help finish it up too.

Thanks for the contribution! :)

**Comment by dkniffin** [comment]
@tscanlin I was hoping to find time to test this, but it seems I was wrong. If you have time to test it and finish it up, that would be awesome. Otherwise, it's not very high on my list of priorities, but I'll get to it at some point.

**Pull request merged**
