### PR TITLE
adding scrollSmoothOffset

### PR DESCRIPTION
**Pull request by regulyarniy**
adding scrollSmoothOffset option for vertical offset when scrolling to position
useful for example when page have sticky header, that overlapping top of the page

### CODE REVIEW

**Comment by tscanlin** [comment]
I have a section in the readme that talks about how to handle fixed headers. Can you try that solution instead?

**Comment by regulyarniy** [comment]
> I have a section in the readme that talks about how to handle fixed headers. Can you try that solution instead?

It's not working in my case. 
Anyway it is better to give user ability to control this option

**Comment by tscanlin** [comment]
Can you share an example? How does your solution handle when the user clicks the back button or reloads the page?

**Comment by regulyarniy** [comment]
> Can you share an example?

https://codesandbox.io/s/w28j2jpvx7
css hack won't work when headings nested in flex container

> How does your solution handle when the user clicks the back button or reloads the page?
 
don't quite understand why you asking this. I just passed new option to jump function, that was set to 0 by default. I'm not handling back button or reload page.

**Comment by tscanlin** [comment]
Thanks for your PR and sorry I’ve been late in responding. I’m currently on vacation for the next 3 weeks but when I return home I can revisit this.

Hope you have a happy start to the new year!

**Comment by regulyarniy** [comment]
> Thanks for your PR and sorry I’ve been late in responding. I’m currently on vacation for the next 3 weeks but when I return home I can revisit this.
> 
> Hope you have a happy start to the new year!

Enjoy your vacation! Happy new year! 🎅⛄⛄⛄

**Pull request merged**
